### ISSUE TITLE
Very broken

### ISSUE THREAD

**Issue by RossComputerGuy** [Meeks91/nodeJS_OAuth2Example#4]
**DO NOT USE THIS REPO**

There are many issues with callbacks being used instead of promises. There's syntax errors too. Not ES6 compatible.

**Comment by bcmyguest** [comment]
lmfao

**Comment by Meeks91** [comment]
This is not a library. It's backing code for a tutorial on how to implement OAuth 2

**Comment by RossComputerGuy** [comment]
I never said it was a library, I was meaning that the example is broken and doesn't work. If you don't want issues like these then this project must be actively maintained. The last time the code was working is back in 2017, that is 4 years ago.
