### ISSUE TITLE
README.md is empty except for a generic description

### ISSUE THREAD

**Issue by noopur-tiwari** [Meeks91/nodeJS_OAuth2Example#6]
Please add details to this file, mainly in terms of flow of execution. Right now it is quite difficult to understand with so many callback functions.

**Comment by Meeks91** [comment]
There is no README details because the repo is designed to accompany a very detailed tutorial here: https://blog.cloudboost.io/how-to-make-an-oauth-2-server-with-node-js-a6db02dc2ce7
